name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Connexion au registre GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker Image avec un tag `latest`
      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/moussa-goita/my-nginx
          docker build . -t $IMAGE_NAME:latest

          # Tag supplémentaire basé sur le commit (optionnel)
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}

      # Push vers GitHub Packages
      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/my-nginx
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
